### ISSUE TITLE
New IL between Ergo and ErgoCalculus

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#223]
The translation between Ergo to ErgoCalculus is trying to do too many things at the same time. An additional intermediate language would help clarify / isolate some of the compilation tasks.

- [x] Add new ErgoCaclulus IL
- [x] Rename old ErgoCaclulus to ErgoNNRC
- [x] Split existing translation in two parts: Ergo to ErgoCalculus and ErgoCalculus to ErgoNNRC
- [x] Remove use of clauses in ErgoNNRC altogether to only use functions instead
- [x] Remove use of clauses in ErgoCalculus altogether to only use functions instead
- [x] Replace contract structure by functions tables in ErgoNNRC
- [x] Investigate replacing contract structure by function tables in ErgoCalculus as well
- [x] Investigate removal of `This*` expressions in ErgoCalculus instead of ErgoNNRC
- [x] Add namespace resolution phase to ~ErgoCalculus~ Ergo AST (See #18 )
- [x] Should Ergo calculus keep a distinction between clauses and functions (e.g., for error reporting)

**Comment by jeromesimeon** [comment]
@kach Any thought on the last two items?

**Comment by kach** [comment]
On distinction between clauses and functions: yes, I think this is important. Even if they effectively do the same thing, I think it is important to make the distinction at a language level, for a bunch of reasons:

1. Better error reporting, as you said
2. It will guide language design decisions so that we don't make the function/clause distinction too confusing (e.g. by having people try to put `emit` in a function rather than a clause)
3. It gives us the opportunity to change how clauses work later on, without doing major surgery on the codebase
4. It will likely simplify typechecking

**Comment by jeromesimeon** [comment]
Final items addressed in PR #268
