### ISSUE TITLE
Clear distinction between Ergo and ErgoCalculus evaluation

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#284]
The current evaluation code covers (parts of) both Ergo and Ergo calculus and should be cleaned up:
- [x] Eval for Ergo
- [x] Eval for ErgoCalculus
- [x] Separate compilation from evaluation

**Comment by kach** [comment]
I'm going to drop support for eval for plain Ergo because it will be painful to maintain two separate versions. It's better to have a clean ergocalculus eval than a sketchy eval that kind of works for both.

What exactly do you mean by "separate compilation from evaluation"? Is this about moving function inlining, etc. to a better place in the pipeline?

**Comment by jeromesimeon** [comment]
About separate compilation from evaluation. I think the main function involved is: https://github.com/accordproject/ergo/blob/3dbc6f54d1206069d6f5ae7a7f3b49ba1d50b5fd/mechanization/Ergo/Lang/ErgoEval.v#L454

This function does two things: compile and eval. It would be better to have an eval which works on pure Ergo calculus declarations, and have the compilation hook in a separate functions at the top-level (e.g., in `./Compiler/ErgoInterpreter.v`).

**Comment by kach** [comment]
(todo move things to different places)

**Comment by jeromesimeon** [comment]
Further cleanup on the third item, which wasn't finished.
