### ISSUE TITLE
Overload some operators

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#375]
Now that we have a proper type checker, we could consider overloading some of the operators and consolidate the syntax for those. Some prime candidates:

```
// Arithmetics
1 +i 1 => 1 + 1
1.0 + 1.0 => 1.0 + 1.0

// Comparisons
1 <i 2 => 1 < 2
1.0 < 2.0 => 1.0 < 2.0

// String concatenation
"hello " ++ "world!" => "hello " + "world!"

// Field access
AccordContractState{ stateId : "123" }.stateId
{ stateId : "123" }.stateId
```

**Comment by kach** [comment]
I'm not sure about doing operator overloading for numbers just yet, because it can get confusinga. We should first sort out the numeric type situation, and then choose operators based on which numeric types will be most common.

In the meantime, if +i bothers you, we can do +. for float addition and + for integer addition, as in OCaml.

I think ++ is okay for string concatenation. Otherwise people will keep trying to do `"The amount is: " + 10` and complaining about the error.

Field access can definitely be overloaded, possibly just by modifying the syntactic sugar? @jeromesimeon what's the top brand in the brand relation? I'm thinking compiling `a.b` to `match a.b with let a : TopBrand then unbrand(a).b else a.b` would work. This strategy would also fix #385 I think.

**Comment by jeromesimeon** [comment]
Some core support for overloaded operators is in place. It's quite conservative, doing static dispatch for clearly identified pairs of types:
```
Double + Double
Integer + Integer
etc.

Double >= Double
Integer >= Integer
etc.

-Integer
-Double
```

It also overloads `.foo` in order to access fields on either records or branded records (aka objects). See #385 

Now that the infrastructure is in place, we can decide to expand on this or not based on user experience and feedback.

**Comment by jeromesimeon** [comment]
Note: `++` is still used for string concatenation. (I personally quite like that it is not confused with `+` which is an arithmetic operator).

Possible other candidates for using operators include:
- Arithmetics and comparisons on `DateTime`
- `arrayAdd` and `arraySubtract`
